const fs = require('fs');
const path = require('path');

const file = path.resolve('src/port-sentinel/App.tsx');
let content = fs.readFileSync(file, 'utf8');

// Remove lucide-react import
content = content.replace(/import\s*\{[^}]*\}\s*from\s*["']lucide-react["'];\n?/gm, '');

const map = {
  '<Upload ': '<Icon icon="lucide:upload" ',
  '<Upload/>': '<Icon icon="lucide:upload" />',
  '<Upload />': '<Icon icon="lucide:upload" />',
  '<Send ': '<Icon icon="lucide:send" ',
  '<Send/>': '<Icon icon="lucide:send" />',
  '<Send />': '<Icon icon="lucide:send" />',
  '<X ': '<Icon icon="lucide:x" ',
  '<X/>': '<Icon icon="lucide:x" />',
  '<X />': '<Icon icon="lucide:x" />',
  '<AlertCircle ': '<Icon icon="lucide:alert-circle" ',
  '<AlertCircle/>': '<Icon icon="lucide:alert-circle" />',
  '<AlertCircle />': '<Icon icon="lucide:alert-circle" />',
  '<Grid ': '<Icon icon="lucide:grid" ',
  '<Grid/>': '<Icon icon="lucide:grid" />',
  '<Grid />': '<Icon icon="lucide:grid" />',
  '<Download ': '<Icon icon="lucide:download" ',
  '<Download/>': '<Icon icon="lucide:download" />',
  '<Download />': '<Icon icon="lucide:download" />',
  '<AlignStartVertical ': '<Icon icon="lucide:align-start-vertical" ',
  '<AlignStartVertical/>': '<Icon icon="lucide:align-start-vertical" />',
  '<AlignStartVertical />': '<Icon icon="lucide:align-start-vertical" />',
  '<AlignEndVertical ': '<Icon icon="lucide:align-end-vertical" ',
  '<AlignEndVertical/>': '<Icon icon="lucide:align-end-vertical" />',
  '<AlignEndVertical />': '<Icon icon="lucide:align-end-vertical" />',
  '<AlignStartHorizontal ': '<Icon icon="lucide:align-start-horizontal" ',
  '<AlignStartHorizontal/>': '<Icon icon="lucide:align-start-horizontal" />',
  '<AlignStartHorizontal />': '<Icon icon="lucide:align-start-horizontal" />',
  '<AlignEndHorizontal ': '<Icon icon="lucide:align-end-horizontal" ',
  '<AlignEndHorizontal/>': '<Icon icon="lucide:align-end-horizontal" />',
  '<AlignEndHorizontal />': '<Icon icon="lucide:align-end-horizontal" />',
  '<AlignCenterVertical ': '<Icon icon="lucide:align-center-vertical" ',
  '<AlignCenterVertical/>': '<Icon icon="lucide:align-center-vertical" />',
  '<AlignCenterVertical />': '<Icon icon="lucide:align-center-vertical" />',
  '<AlignCenterHorizontal ': '<Icon icon="lucide:align-center-horizontal" ',
  '<AlignCenterHorizontal/>': '<Icon icon="lucide:align-center-horizontal" />',
  '<AlignCenterHorizontal />': '<Icon icon="lucide:align-center-horizontal" />',
  '<LayoutGrid ': '<Icon icon="lucide:layout-grid" ',
  '<LayoutGrid/>': '<Icon icon="lucide:layout-grid" />',
  '<LayoutGrid />': '<Icon icon="lucide:layout-grid" />',
  '<Undo2 ': '<Icon icon="lucide:undo-2" ',
  '<Undo2/>': '<Icon icon="lucide:undo-2" />',
  '<Undo2 />': '<Icon icon="lucide:undo-2" />',
  '<Redo2 ': '<Icon icon="lucide:redo-2" ',
  '<Redo2/>': '<Icon icon="lucide:redo-2" />',
  '<Redo2 />': '<Icon icon="lucide:redo-2" />',
  '<Trash2 ': '<Icon icon="lucide:trash-2" ',
  '<Trash2/>': '<Icon icon="lucide:trash-2" />',
  '<Trash2 />': '<Icon icon="lucide:trash-2" />',
  '<HistoryIcon ': '<Icon icon="lucide:history" ',
  '<HistoryIcon/>': '<Icon icon="lucide:history" />',
  '<HistoryIcon />': '<Icon icon="lucide:history" />',
  '<ChevronDown ': '<Icon icon="lucide:chevron-down" ',
  '<ChevronDown/>': '<Icon icon="lucide:chevron-down" />',
  '<ChevronDown />': '<Icon icon="lucide:chevron-down" />',
  '<ChevronRight ': '<Icon icon="lucide:chevron-right" ',
  '<ChevronRight/>': '<Icon icon="lucide:chevron-right" />',
  '<ChevronRight />': '<Icon icon="lucide:chevron-right" />',
  '<AlignHorizontalSpaceBetween ': '<Icon icon="lucide:align-horizontal-space-between" ',
  '<AlignHorizontalSpaceBetween/>': '<Icon icon="lucide:align-horizontal-space-between" />',
  '<AlignHorizontalSpaceBetween />': '<Icon icon="lucide:align-horizontal-space-between" />',
  '<AlignVerticalSpaceBetween ': '<Icon icon="lucide:align-vertical-space-between" ',
  '<AlignVerticalSpaceBetween/>': '<Icon icon="lucide:align-vertical-space-between" />',
  '<AlignVerticalSpaceBetween />': '<Icon icon="lucide:align-vertical-space-between" />',
  '<ZoomIn ': '<Icon icon="lucide:zoom-in" ',
  '<ZoomIn/>': '<Icon icon="lucide:zoom-in" />',
  '<ZoomIn />': '<Icon icon="lucide:zoom-in" />',
  '<ZoomOut ': '<Icon icon="lucide:zoom-out" ',
  '<ZoomOut/>': '<Icon icon="lucide:zoom-out" />',
  '<ZoomOut />': '<Icon icon="lucide:zoom-out" />',
  '<Crop ': '<Icon icon="lucide:crop" ',
  '<Crop/>': '<Icon icon="lucide:crop" />',
  '<Crop />': '<Icon icon="lucide:crop" />',
  '<Lock ': '<Icon icon="lucide:lock" ',
  '<Lock/>': '<Icon icon="lucide:lock" />',
  '<Lock />': '<Icon icon="lucide:lock" />',
  '<Unlock ': '<Icon icon="lucide:unlock" ',
  '<Unlock/>': '<Icon icon="lucide:unlock" />',
  '<Unlock />': '<Icon icon="lucide:unlock" />',
};

for (const [key, value] of Object.entries(map)) {
  content = content.split(key).join(value);
}

fs.writeFileSync(file, content, 'utf8');
console.log('Icons replaced successfully.');
